name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          dpkg-dev \
          rpm \
          lcov
        
    - name: Configure project
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON
      
    - name: Build project
      run: cmake --build build --config Release --parallel $(nproc)
      
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
        
    - name: Generate coverage report
      if: success() && matrix.coverage == 'ON'
      run: |
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info
        genhtml coverage.info --output-directory coverage_report
        
    - name: Create packages
      run: |
        cd build
        cpack -G TGZ
        cpack -G DEB
        cpack -G RPM
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-packages
        path: |
          build/*.tar.gz
          build/*.deb
          build/*.rpm
          build/coverage_report/**
        retention-days: 5

  windows-build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install WiX Toolset
      run: choco install wixtoolset -y
      
    - name: Configure project
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON
      
    - name: Build project
      run: cmake --build build --config Release --parallel 2
      
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
        
    - name: Create MSI package
      run: |
        cd build
        cpack -G WIX
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-packages
        path: |
          build/*.msi
          build/Testing/**
        retention-days: 5

  macos-build:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Configure project
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON
      
    - name: Build project
      run: cmake --build build --config Release --parallel 2
      
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
        
    - name: Create DMG package
      run: |
        cd build
        cpack -G DragNDrop
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-packages
        path: |
          build/*.dmg
          build/Testing/**
        retention-days: 5
